name: eeg-project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.5
  - torchvision
  - torchaudio
  - pytorch-cuda=12.6
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - jupyterlab
  - ipykernel
  - mne
  - pip
  - pip:
    - transformers>=4.40
    - einops
    - wandb
    - bert-score
    - peft
